service: serverless-ghostbuster-slack

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

functions:
  app:
    handler: handler.app
    events:
      - http:
          method: post
          path: /slack/events
